### ISSUE TITLE
这个预览或者生成，在移动端怎么实现？有demo可以学习下吗

### ISSUE THREAD

**Issue by wangdong1209** [wxjaa/ddvue#3]

**Comment by wxjaa** [comment]
这个就是对每个组件都写好对应的移动端展示组件，做好对应的逻辑处理，然后等后端吧数据返回的时候判断组件名，根据不同的组件名展示对应的移动端展示组件就可以了



------------------ 原始邮件 ------------------
发件人: "wangdong1209"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 上午10:45
收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)



 
&mdash;

**Comment by wangdong1209** [comment]
我现在要实现移动端那边,需求比较复杂，想找个移动端实现demo研究哈




------------------ 原始邮件 ------------------
发件人: "wxjaa"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 上午10:49
收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)



这个就是对每个组件都写好对应的移动端展示组件，做好对应的逻辑处理，然后等后端吧数据返回的时候判断组件名，根据不同的组件名展示对应的移动端展示组件就可以了 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wangdong1209"<notifications@github.com>;  
 发送时间: 2019年9月18日(星期三) 上午10:45 
 收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;  
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 主题: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3) 
 
 
 
   
 &mdash;

**Comment by wxjaa** [comment]
思路大概就是这样的，demo我没有写



------------------ 原始邮件 ------------------
发件人: "wangdong1209"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 上午10:51
收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>; 
抄送: "789"<980607279@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)



我现在要实现移动端那边,需求比较复杂，想找个移动端实现demo研究哈 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wxjaa"<notifications@github.com>;  
 发送时间: 2019年9月18日(星期三) 上午10:49 
 收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;  
 抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3) 
 
 
 
 这个就是对每个组件都写好对应的移动端展示组件，做好对应的逻辑处理，然后等后端吧数据返回的时候判断组件名，根据不同的组件名展示对应的移动端展示组件就可以了  
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "wangdong1209"<notifications@github.com>;   
  发送时间: 2019年9月18日(星期三) 上午10:45  
  收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;   
  抄送: "Subscribed"<subscribed@noreply.github.com>;   
  主题: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)  
   
   
   
     
  &mdash;

**Comment by wangdong1209** [comment]
好吧，谢啦



------------------ 原始邮件 ------------------
发件人: "wxjaa"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 上午10:54
收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>; 
抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)



思路大概就是这样的，demo我没有写 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wangdong1209"<notifications@github.com>;  
 发送时间: 2019年9月18日(星期三) 上午10:51 
 收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;  
 抄送: "789"<980607279@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3) 
 
 
 
 我现在要实现移动端那边,需求比较复杂，想找个移动端实现demo研究哈  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "wxjaa"<notifications@github.com>;   
  发送时间: 2019年9月18日(星期三) 上午10:49  
  收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;   
  抄送: "水月流星"<542495420@qq.com>; "Author"<author@noreply.github.com>;   
  主题: Re: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)  
   
   
   
  这个就是对每个组件都写好对应的移动端展示组件，做好对应的逻辑处理，然后等后端吧数据返回的时候判断组件名，根据不同的组件名展示对应的移动端展示组件就可以了   
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "wangdong1209"<notifications@github.com>;    
   发送时间: 2019年9月18日(星期三) 上午10:45   
   收件人: "wxjaa/ddvue"<ddvue@noreply.github.com>;    
   抄送: "Subscribed"<subscribed@noreply.github.com>;    
   主题: [wxjaa/ddvue] 这个预览或者生成，在移动端怎么实现？有demo可以学习下吗 (#3)   
     
     
     
       
   &mdash;
